title: 暮らしの手順書
description: >-
  日々の生活の記録  
  書かれていることはすべて個人の見解です
baseurl: "/kurashino"
url: "https://yuki-kamikita.github.io"
permalink: /:categories/:title.html
author: yuki_kamikita

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-archives

markdown: kramdown

sass_dir: assets/css

jekyll-archives:
  enabled:
    - categories
    - tags
  layouts:
    category: category
    tag: tag
  permalinks:
    category: /category/:name/
    tag: /tag/:name/
