title: 暮らしの手順書
description: >-
  日々の生活の記録  
  書かれていることはすべて個人の見解です
baseurl: "/kurashino"
url: "https://yuki-kamikita.github.io"
author: yuki_kamikita

theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-archives

sass:
  style: expanded

jekyll-archives:
  enabled:
    - categories
  layouts:
    category: category
  permalinks:
    category: /category/:name/