title: 暮らしの手順書
description: >-
  日々の生活の記録  
  書かれていることはすべて個人の見解です
baseurl: ""
url: ""
author: yuki_kamikita

theme: minima
plugins:
  - jekyll-feed

sass:
  style: expanded

gems:
  - jekyll-paginate
  - jekyll-feed